import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BrainCards",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico"></link>
        <Script
          strategy='afterInteractive'
          src={`https://www.googletagmanager.com/gtag/js?id=G-FQKYC9ZQT0`}
        />

        <Script id='' strategy='afterInteractive'>
          {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', 'G-FQKYC9ZQT0', {
                page_path: window.location.pathname,
                });
            `}
        </Script>
      </head>
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
    
  );
}
